sudo: required
services:
  - docker

before_install: 
  - docker build -t billpruett/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true billpruett/react-test npm test

after_success:
  - docker build -t billpruett/multi-client ./client
  - docker build -t billpruett/multi-nginx ./nginx
  - docker build -t billpruett/multi-server ./server
  - docker build -t billpruett/multi-worker ./worker
  